import { type Locale } from "../../../i18n/routing";

import { type ServiceCopy } from "./shared";

/** Flagship service — fully authored from the design, translated per locale. */
export const destinationWeddingPlanning: Record<Locale, ServiceCopy> = {
  en: {
    name: "Destination Wedding Planning",
    summary:
      "Full-service curation from continent to plate, eighteen-to-twenty-four months in advance.",
    hero: {
      eyebrow: "Services · No. 01",
      scriptOverline: "The full",
      headline: "destination *planning.*",
      deck: "The complete engagement — eighteen-to-twenty-four months, end to end, from the first conversation to the morning-after brunch.",
      captionLeft: "The studio's flagship service",
      captionCenter: "Full-service · two planners per wedding",
      captionRight: "Plate I",
    },
    overview: {
      eyebrow: "The service",
      headline: "From continent to *plate.*",
      lede: "Destination wedding planning is the studio's flagship — the full engagement, where we hold every part of the wedding from the first conversation to the last farewell.",
      bodyParagraphs: [
        "A destination wedding is not a local wedding moved abroad. It is a different discipline: a travelling guest list, a venue you cannot visit on a whim, vendors in a foreign language, legal requirements that change at every border, and a calendar measured in years rather than months.",
        "We have planned this wedding two hundred and forty times. We know which resorts overstate their capacity, which airports clear floral imports without delay, and how to hold a four-day arc together when three hundred guests are travelling from three continents.",
      ],
      captionLine1: "Cap Cana · February 2025",
      captionLine2: "The Saira & Adam wedding",
    },
    inclusions: {
      eyebrow: "What it includes",
      headline: "Held, *end to end.*",
      deck: "The full-service engagement folds in every one of the studio's specialist services as standard.",
      items: [
        { title: "Venue sourcing", body: "A shortlist of three-to-five houses, scouted in person, matched to your guest count and the wedding you are imagining." },
        { title: "Design & art direction", body: "Florals, tablescape, lighting, scent, sound — a complete visual concept built bespoke for the wedding." },
        { title: "Cultural protocol", body: "Officiants, choreographers and caterers for any tradition, coordinated by our cultural specialists." },
        { title: "Guest logistics", body: "Room blocks, transfers, welcome desks, excursions, gifting and farewell brunches — the full travelling-guest experience." },
        { title: "Legal & paperwork", body: "Marriage licenses, apostilles, customs clearance for florals and ceremonial objects, multi-country compliance." },
        { title: "Production", body: "Stage, sound, lighting, AV, fabrication and fireworks — run by the studio's own production team." },
        { title: "Budget & vendor management", body: "A transparent line-item budget, contracts reviewed, vendors managed, payments scheduled." },
        { title: "On-site direction", body: "Grecia and a second planner on site for every event of every day. Nothing delegated past the studio." },
        { title: "The year between", body: "Monthly check-ins, a shared planning portal, and a single point of contact who knows your wedding by heart." },
      ],
    },
    process: {
      eyebrow: "The process",
      headline: "Six *movements.*",
      deck: "How a destination wedding moves from first conversation to the morning-after brunch, across eighteen-to-twenty-four months.",
      steps: [
        { numeral: "I", title: "The conversation", when: "24 – 22 months out", body: "A private consultation, two-to-three hours. We listen — to you, to your families, to the wedding you are imagining — and we tell you honestly what is possible." },
        { numeral: "II", title: "Concept & venue", when: "22 – 18 months out", body: "A written concept, a working budget, and a shortlist of venues scouted in person. We refine until the direction is right, then secure the date." },
        { numeral: "III", title: "Design & sourcing", when: "18 – 10 months out", body: "The bespoke design develops — florals, tablescape, palette, production. Cultural specialists are engaged. Vendors are contracted by name." },
        { numeral: "IV", title: "Logistics & guests", when: "10 – 4 months out", body: "Room blocks, transfers, the guest portal, dietary mapping, legal paperwork. The four-day arc is rehearsed on paper, hour by hour." },
        { numeral: "V", title: "The wedding", when: "The weekend itself", body: "Grecia and a second planner on site for every event of every day. The studio holds the wedding so the family does not have to." },
        { numeral: "VI", title: "The farewell", when: "After", body: "The morning-after brunch, departures, and a final gift. The wedding closes the way it began — quietly, by hand." },
      ],
    },
    audience: {
      eyebrow: "Who it is for",
      headline: "Is this *for you?*",
      items: [
        { title: "Couples marrying abroad", body: "A wedding in a country neither of you lives in — where you need a studio that knows the ground." },
        { title: "Forty to eight hundred guests", body: "Our minimum is forty. Below that, we will refer you, warmly, to a studio that specialises in elopements." },
        { title: "Eighteen months or more", body: "The full service needs time. If you are inside a year, talk to us — but the calendar shrinks." },
        { title: "Multi-day, often multicultural", body: "Most of our weddings span three-to-five days, and roughly half braid two cultures or two religions." },
        { title: "Couples who want to be guests", body: "At their own wedding. The studio holds the work so you can be present for it." },
      ],
    },
    faq: {
      eyebrow: "Questions, answered",
      headline: "Frequently *asked.*",
      items: [
        { question: "What does the full planning service cost?", answer: ["The studio works on a flat planning fee, scaled to the wedding — typically 12–18% of the total wedding budget, agreed up front with no commission on vendors. We share a transparent line-item budget in the first proposal, and we never take a hidden margin on a florist or a caterer."] },
        { question: "How many weddings do you take at once?", answer: ["Fourteen per year, across the whole studio. Each is assigned two planners who hold it from first conversation to farewell. We cap the calendar deliberately — it is the only way to be on site for every event of every day."] },
        { question: "Can we book you if we already have a venue?", answer: ["Yes. Many couples come to us with a venue already chosen. We fold our other services — design, cultural protocol, production, guest experience — around the venue you have. The planning fee adjusts accordingly."] },
        { question: "Do you travel anywhere, or only Punta Cana?", answer: ["We are based in Punta Cana and Milan, and we travel worldwide. Roughly half our weddings are in the Caribbean; the rest span Italy, France, Spain, Greece, the wider Caribbean, and occasionally further."] },
        { question: "How far in advance should we engage you?", answer: ["Eighteen-to-twenty-four months is ideal. It gives time to secure the right venue, develop a bespoke design, and rehearse the logistics properly. We have planned weddings in six months — but the calendar, and the venue options, shrink quickly."] },
      ],
    },
    cta: {
      eyebrow: "A private conversation —",
      headline: "*Begin* your wedding journey.",
      body: "Tell us the wedding you are imagining, the destination, and a rough date. Grecia writes back, personally, within five working days.",
      ctaLabel: "Request a private consultation →",
    },
  },

  es: {
    name: "Planificación de Bodas de Destino",
    summary:
      "Curaduría integral, del continente al plato, con dieciocho a veinticuatro meses de antelación.",
    hero: {
      eyebrow: "Servicios · N.º 01",
      scriptOverline: "La",
      headline: "planificación *integral.*",
      deck: "El encargo completo — de dieciocho a veinticuatro meses, de principio a fin, desde la primera conversación hasta el brunch de la mañana siguiente.",
      captionLeft: "El servicio insignia del atelier",
      captionCenter: "Servicio integral · dos planificadores por boda",
      captionRight: "Lámina I",
    },
    overview: {
      eyebrow: "El servicio",
      headline: "Del continente al *plato.*",
      lede: "La planificación de bodas de destino es la insignia del atelier — el encargo completo, donde sostenemos cada parte de la boda desde la primera conversación hasta la última despedida.",
      bodyParagraphs: [
        "Una boda de destino no es una boda local trasladada al extranjero. Es una disciplina distinta: una lista de invitados que viaja, un lugar que no se puede visitar por capricho, proveedores en otro idioma, requisitos legales que cambian en cada frontera y un calendario medido en años y no en meses.",
        "Hemos planificado esta boda doscientas cuarenta veces. Sabemos qué resorts exageran su capacidad, qué aeropuertos despachan las importaciones florales sin demora y cómo sostener un arco de cuatro días cuando trescientos invitados viajan desde tres continentes.",
      ],
      captionLine1: "Cap Cana · Febrero de 2025",
      captionLine2: "La boda de Saira y Adam",
    },
    inclusions: {
      eyebrow: "Qué incluye",
      headline: "Sostenido, *de principio a fin.*",
      deck: "El encargo integral incorpora de serie cada uno de los servicios especializados del atelier.",
      items: [
        { title: "Búsqueda de locaciones", body: "Una preselección de tres a cinco casas, exploradas en persona, ajustadas a tu número de invitados y a la boda que imaginas." },
        { title: "Diseño y dirección de arte", body: "Flores, mesa, iluminación, aroma, sonido — un concepto visual completo creado a medida para la boda." },
        { title: "Protocolo cultural", body: "Oficiantes, coreógrafos y caterings para cualquier tradición, coordinados por nuestros especialistas culturales." },
        { title: "Logística de invitados", body: "Bloques de habitaciones, traslados, mostradores de bienvenida, excursiones, regalos y brunches de despedida — la experiencia completa del invitado que viaja." },
        { title: "Legal y trámites", body: "Licencias de matrimonio, apostillas, despacho aduanero de flores y objetos ceremoniales, cumplimiento en varios países." },
        { title: "Producción", body: "Escenario, sonido, iluminación, audiovisuales, fabricación y fuegos artificiales — a cargo del propio equipo de producción del atelier." },
        { title: "Presupuesto y proveedores", body: "Un presupuesto transparente por partidas, contratos revisados, proveedores gestionados, pagos programados." },
        { title: "Dirección in situ", body: "Grecia y un segundo planificador presentes en cada evento de cada día. Nada se delega más allá del atelier." },
        { title: "El año intermedio", body: "Reuniones mensuales, un portal de planificación compartido y un único punto de contacto que conoce tu boda de memoria." },
      ],
    },
    process: {
      eyebrow: "El proceso",
      headline: "Seis *movimientos.*",
      deck: "Cómo avanza una boda de destino desde la primera conversación hasta el brunch de la mañana siguiente, a lo largo de dieciocho a veinticuatro meses.",
      steps: [
        { numeral: "I", title: "La conversación", when: "24 – 22 meses antes", body: "Una consulta privada, de dos a tres horas. Escuchamos — a ti, a tus familias, a la boda que imaginas — y te decimos con honestidad qué es posible." },
        { numeral: "II", title: "Concepto y lugar", when: "22 – 18 meses antes", body: "Un concepto por escrito, un presupuesto de trabajo y una preselección de lugares explorados en persona. Afinamos hasta que la dirección es la correcta y aseguramos la fecha." },
        { numeral: "III", title: "Diseño y selección", when: "18 – 10 meses antes", body: "El diseño a medida se desarrolla — flores, mesa, paleta, producción. Se incorporan los especialistas culturales. Los proveedores se contratan por su nombre." },
        { numeral: "IV", title: "Logística e invitados", when: "10 – 4 meses antes", body: "Bloques de habitaciones, traslados, el portal de invitados, mapa de dietas, trámites legales. El arco de cuatro días se ensaya sobre el papel, hora a hora." },
        { numeral: "V", title: "La boda", when: "El fin de semana", body: "Grecia y un segundo planificador en cada evento de cada día. El atelier sostiene la boda para que la familia no tenga que hacerlo." },
        { numeral: "VI", title: "La despedida", when: "Después", body: "El brunch de la mañana siguiente, las salidas y un último regalo. La boda se cierra como empezó — en silencio, a mano." },
      ],
    },
    audience: {
      eyebrow: "Para quién es",
      headline: "¿Es esto *para ti?*",
      items: [
        { title: "Parejas que se casan fuera", body: "Una boda en un país donde ninguno de los dos vive — donde necesitas un atelier que conozca el terreno." },
        { title: "De cuarenta a ochocientos invitados", body: "Nuestro mínimo es cuarenta. Por debajo de esa cifra, te derivamos con gusto a un atelier especializado en fugas de boda." },
        { title: "Dieciocho meses o más", body: "El servicio integral necesita tiempo. Si estás dentro del año, habla con nosotros — pero el calendario se estrecha." },
        { title: "De varios días, a menudo multicultural", body: "La mayoría de nuestras bodas duran de tres a cinco días, y cerca de la mitad entrelazan dos culturas o dos religiones." },
        { title: "Parejas que quieren ser invitadas", body: "En su propia boda. El atelier sostiene el trabajo para que puedas estar presente en ella." },
      ],
    },
    faq: {
      eyebrow: "Preguntas, respondidas",
      headline: "Preguntas *frecuentes.*",
      items: [
        { question: "¿Cuánto cuesta el servicio de planificación integral?", answer: ["El atelier trabaja con una tarifa plana de planificación, ajustada a la boda — normalmente entre el 12 y el 18 % del presupuesto total, acordada de antemano y sin comisión sobre los proveedores. Compartimos un presupuesto transparente por partidas en la primera propuesta, y nunca tomamos un margen oculto sobre un florista o un catering."] },
        { question: "¿Cuántas bodas aceptan a la vez?", answer: ["Catorce al año, en todo el atelier. A cada una se le asignan dos planificadores que la sostienen desde la primera conversación hasta la despedida. Limitamos el calendario a propósito — es la única forma de estar presentes en cada evento de cada día."] },
        { question: "¿Pueden contratarnos si ya tenemos lugar?", answer: ["Sí. Muchas parejas llegan con el lugar ya elegido. Adaptamos nuestros demás servicios — diseño, protocolo cultural, producción, experiencia del invitado — al lugar que tienes. La tarifa de planificación se ajusta en consecuencia."] },
        { question: "¿Viajan a cualquier lugar o solo a Punta Cana?", answer: ["Tenemos base en Punta Cana y Milán, y viajamos por todo el mundo. Cerca de la mitad de nuestras bodas son en el Caribe; el resto abarca Italia, Francia, España, Grecia, el Caribe más amplio y, en ocasiones, más allá."] },
        { question: "¿Con cuánta antelación deberíamos contratarlos?", answer: ["De dieciocho a veinticuatro meses es lo ideal. Da tiempo para asegurar el lugar adecuado, desarrollar un diseño a medida y ensayar la logística como es debido. Hemos planificado bodas en seis meses — pero el calendario, y las opciones de lugar, se estrechan deprisa."] },
      ],
    },
    cta: {
      eyebrow: "Una conversación privada —",
      headline: "*Comienza* tu viaje nupcial.",
      body: "Cuéntanos la boda que imaginas, el destino y una fecha aproximada. Grecia responde personalmente en cinco días laborables.",
      ctaLabel: "Solicitar una consulta privada →",
    },
  },

  fr: {
    name: "Organisation de Mariage de Destination",
    summary:
      "Une curation intégrale, du continent à l'assiette, dix-huit à vingt-quatre mois à l'avance.",
    hero: {
      eyebrow: "Services · N° 01",
      scriptOverline: "L'organisation",
      headline: "*intégrale.*",
      deck: "L'engagement complet — dix-huit à vingt-quatre mois, du début à la fin, de la première conversation au brunch du lendemain.",
      captionLeft: "Le service phare de l'atelier",
      captionCenter: "Service intégral · deux organisateurs par mariage",
      captionRight: "Planche I",
    },
    overview: {
      eyebrow: "Le service",
      headline: "Du continent à *l'assiette.*",
      lede: "L'organisation de mariage de destination est le service phare de l'atelier — l'engagement complet, où nous portons chaque partie du mariage, de la première conversation au dernier adieu.",
      bodyParagraphs: [
        "Un mariage de destination n'est pas un mariage local déplacé à l'étranger. C'est une autre discipline : une liste d'invités qui voyage, un lieu que l'on ne peut visiter sur un coup de tête, des prestataires dans une autre langue, des exigences légales qui changent à chaque frontière, et un calendrier qui se compte en années plutôt qu'en mois.",
        "Nous avons organisé ce mariage deux cent quarante fois. Nous savons quels resorts surestiment leur capacité, quels aéroports dédouanent les importations florales sans délai, et comment tenir une trame de quatre jours lorsque trois cents invités voyagent depuis trois continents.",
      ],
      captionLine1: "Cap Cana · Février 2025",
      captionLine2: "Le mariage de Saira & Adam",
    },
    inclusions: {
      eyebrow: "Ce qu'il comprend",
      headline: "Porté, *du début à la fin.*",
      deck: "L'engagement intégral inclut d'office chacun des services spécialisés de l'atelier.",
      items: [
        { title: "Recherche de lieux", body: "Une présélection de trois à cinq demeures, repérées en personne, accordées à votre nombre d'invités et au mariage que vous imaginez." },
        { title: "Design & direction artistique", body: "Fleurs, art de la table, lumière, parfum, son — un concept visuel complet conçu sur mesure pour le mariage." },
        { title: "Protocole culturel", body: "Officiants, chorégraphes et traiteurs pour toute tradition, coordonnés par nos spécialistes culturels." },
        { title: "Logistique des invités", body: "Blocs de chambres, transferts, comptoirs d'accueil, excursions, cadeaux et brunchs d'adieu — l'expérience complète de l'invité qui voyage." },
        { title: "Juridique & démarches", body: "Licences de mariage, apostilles, dédouanement des fleurs et objets cérémoniels, conformité multi-pays." },
        { title: "Production", body: "Scène, son, lumière, audiovisuel, fabrication et feux d'artifice — assurés par la propre équipe de production de l'atelier." },
        { title: "Budget & prestataires", body: "Un budget transparent ligne par ligne, des contrats relus, des prestataires gérés, des paiements programmés." },
        { title: "Direction sur place", body: "Grecia et un second organisateur présents à chaque événement de chaque journée. Rien n'est délégué au-delà de l'atelier." },
        { title: "L'année intermédiaire", body: "Des points mensuels, un portail de planification partagé et un interlocuteur unique qui connaît votre mariage par cœur." },
      ],
    },
    process: {
      eyebrow: "Le processus",
      headline: "Six *mouvements.*",
      deck: "Comment un mariage de destination avance de la première conversation au brunch du lendemain, sur dix-huit à vingt-quatre mois.",
      steps: [
        { numeral: "I", title: "La conversation", when: "24 – 22 mois avant", body: "Une consultation privée, de deux à trois heures. Nous écoutons — vous, vos familles, le mariage que vous imaginez — et nous vous disons honnêtement ce qui est possible." },
        { numeral: "II", title: "Concept & lieu", when: "22 – 18 mois avant", body: "Un concept écrit, un budget de travail et une présélection de lieux repérés en personne. Nous affinons jusqu'à ce que la direction soit juste, puis nous réservons la date." },
        { numeral: "III", title: "Design & sourcing", when: "18 – 10 mois avant", body: "Le design sur mesure se développe — fleurs, art de la table, palette, production. Les spécialistes culturels sont engagés. Les prestataires sont contractés nommément." },
        { numeral: "IV", title: "Logistique & invités", when: "10 – 4 mois avant", body: "Blocs de chambres, transferts, portail des invités, cartographie des régimes, démarches légales. La trame de quatre jours est répétée sur le papier, heure par heure." },
        { numeral: "V", title: "Le mariage", when: "Le week-end même", body: "Grecia et un second organisateur à chaque événement de chaque journée. L'atelier tient le mariage pour que la famille n'ait pas à le faire." },
        { numeral: "VI", title: "L'adieu", when: "Après", body: "Le brunch du lendemain, les départs et un dernier cadeau. Le mariage se referme comme il a commencé — discrètement, à la main." },
      ],
    },
    audience: {
      eyebrow: "À qui il s'adresse",
      headline: "Est-ce *pour vous ?*",
      items: [
        { title: "Couples se mariant à l'étranger", body: "Un mariage dans un pays où aucun de vous ne vit — où vous avez besoin d'un atelier qui connaît le terrain." },
        { title: "De quarante à huit cents invités", body: "Notre minimum est de quarante. En dessous, nous vous orientons, chaleureusement, vers un atelier spécialisé dans les mariages intimes." },
        { title: "Dix-huit mois ou plus", body: "Le service intégral demande du temps. Si vous êtes à moins d'un an, parlez-nous-en — mais le calendrier se resserre." },
        { title: "Sur plusieurs jours, souvent multiculturel", body: "La plupart de nos mariages s'étendent sur trois à cinq jours, et près de la moitié tressent deux cultures ou deux religions." },
        { title: "Des couples qui veulent être invités", body: "À leur propre mariage. L'atelier porte le travail pour que vous puissiez y être présents." },
      ],
    },
    faq: {
      eyebrow: "Questions, réponses",
      headline: "Questions *fréquentes.*",
      items: [
        { question: "Combien coûte le service d'organisation intégrale ?", answer: ["L'atelier travaille sur un forfait d'organisation, proportionné au mariage — généralement de 12 à 18 % du budget total, convenu d'avance et sans commission sur les prestataires. Nous partageons un budget transparent ligne par ligne dès la première proposition, et nous ne prenons jamais de marge cachée sur un fleuriste ou un traiteur."] },
        { question: "Combien de mariages prenez-vous en même temps ?", answer: ["Quatorze par an, pour l'ensemble de l'atelier. Chacun se voit attribuer deux organisateurs qui le portent de la première conversation à l'adieu. Nous plafonnons le calendrier délibérément — c'est la seule façon d'être présents à chaque événement de chaque journée."] },
        { question: "Pouvez-vous nous accompagner si nous avons déjà un lieu ?", answer: ["Oui. De nombreux couples viennent avec un lieu déjà choisi. Nous adaptons nos autres services — design, protocole culturel, production, expérience des invités — autour du lieu que vous avez. Le forfait d'organisation s'ajuste en conséquence."] },
        { question: "Voyagez-vous partout, ou seulement à Punta Cana ?", answer: ["Nous sommes basés à Punta Cana et à Milan, et nous voyageons dans le monde entier. Près de la moitié de nos mariages ont lieu aux Caraïbes ; le reste couvre l'Italie, la France, l'Espagne, la Grèce, les Caraïbes au sens large et, parfois, au-delà."] },
        { question: "Combien de temps à l'avance faut-il nous engager ?", answer: ["Dix-huit à vingt-quatre mois, c'est l'idéal. Cela laisse le temps de réserver le bon lieu, de développer un design sur mesure et de répéter la logistique correctement. Nous avons organisé des mariages en six mois — mais le calendrier, et les options de lieu, se resserrent vite."] },
      ],
    },
    cta: {
      eyebrow: "Une conversation privée —",
      headline: "*Commencez* votre parcours nuptial.",
      body: "Dites-nous le mariage que vous imaginez, la destination et une date approximative. Grecia vous répond personnellement sous cinq jours ouvrés.",
      ctaLabel: "Demander une consultation privée →",
    },
  },

  pt: {
    name: "Planeamento de Casamentos de Destino",
    summary:
      "Curadoria integral, do continente ao prato, com dezoito a vinte e quatro meses de antecedência.",
    hero: {
      eyebrow: "Serviços · N.º 01",
      scriptOverline: "O planeamento",
      headline: "*integral.*",
      deck: "O compromisso completo — dezoito a vinte e quatro meses, do início ao fim, da primeira conversa ao brunch da manhã seguinte.",
      captionLeft: "O serviço de eleição do ateliê",
      captionCenter: "Serviço integral · dois planeadores por casamento",
      captionRight: "Estampa I",
    },
    overview: {
      eyebrow: "O serviço",
      headline: "Do continente ao *prato.*",
      lede: "O planeamento de casamentos de destino é o serviço de eleição do ateliê — o compromisso completo, em que sustentamos cada parte do casamento desde a primeira conversa até à última despedida.",
      bodyParagraphs: [
        "Um casamento de destino não é um casamento local transferido para o estrangeiro. É uma disciplina diferente: uma lista de convidados que viaja, um espaço que não se pode visitar por capricho, fornecedores noutra língua, requisitos legais que mudam em cada fronteira e um calendário medido em anos e não em meses.",
        "Já planeámos este casamento duzentas e quarenta vezes. Sabemos que resorts exageram a sua capacidade, que aeroportos despacham as importações florais sem demora e como sustentar um arco de quatro dias quando trezentos convidados viajam de três continentes.",
      ],
      captionLine1: "Cap Cana · Fevereiro de 2025",
      captionLine2: "O casamento de Saira & Adam",
    },
    inclusions: {
      eyebrow: "O que inclui",
      headline: "Sustentado, *do início ao fim.*",
      deck: "O compromisso integral incorpora de série cada um dos serviços especializados do ateliê.",
      items: [
        { title: "Seleção de locais", body: "Uma pré-seleção de três a cinco casas, exploradas pessoalmente, ajustadas ao seu número de convidados e ao casamento que imagina." },
        { title: "Design e direção de arte", body: "Flores, mesa, iluminação, aroma, som — um conceito visual completo criado à medida para o casamento." },
        { title: "Protocolo cultural", body: "Celebrantes, coreógrafos e caterings para qualquer tradição, coordenados pelos nossos especialistas culturais." },
        { title: "Logística de convidados", body: "Blocos de quartos, transferes, balcões de boas-vindas, excursões, ofertas e brunches de despedida — a experiência completa do convidado que viaja." },
        { title: "Jurídico e papelada", body: "Licenças de casamento, apostilas, desalfandegamento de flores e objetos cerimoniais, conformidade em vários países." },
        { title: "Produção", body: "Palco, som, iluminação, audiovisuais, fabricação e fogo de artifício — a cargo da própria equipa de produção do ateliê." },
        { title: "Orçamento e fornecedores", body: "Um orçamento transparente por rubricas, contratos revistos, fornecedores geridos, pagamentos agendados." },
        { title: "Direção no local", body: "Grecia e um segundo planeador presentes em cada evento de cada dia. Nada é delegado para além do ateliê." },
        { title: "O ano intermédio", body: "Reuniões mensais, um portal de planeamento partilhado e um único ponto de contacto que conhece o seu casamento de cor." },
      ],
    },
    process: {
      eyebrow: "O processo",
      headline: "Seis *movimentos.*",
      deck: "Como um casamento de destino avança da primeira conversa ao brunch da manhã seguinte, ao longo de dezoito a vinte e quatro meses.",
      steps: [
        { numeral: "I", title: "A conversa", when: "24 – 22 meses antes", body: "Uma consulta privada, de duas a três horas. Ouvimos — a si, às suas famílias, ao casamento que imagina — e dizemos-lhe com honestidade o que é possível." },
        { numeral: "II", title: "Conceito e espaço", when: "22 – 18 meses antes", body: "Um conceito escrito, um orçamento de trabalho e uma pré-seleção de espaços explorados pessoalmente. Refinamos até a direção estar certa e asseguramos a data." },
        { numeral: "III", title: "Design e seleção", when: "18 – 10 meses antes", body: "O design à medida desenvolve-se — flores, mesa, paleta, produção. Os especialistas culturais são envolvidos. Os fornecedores são contratados pelo nome." },
        { numeral: "IV", title: "Logística e convidados", when: "10 – 4 meses antes", body: "Blocos de quartos, transferes, o portal de convidados, mapa de dietas, papelada legal. O arco de quatro dias é ensaiado no papel, hora a hora." },
        { numeral: "V", title: "O casamento", when: "O fim de semana", body: "Grecia e um segundo planeador em cada evento de cada dia. O ateliê sustenta o casamento para que a família não tenha de o fazer." },
        { numeral: "VI", title: "A despedida", when: "Depois", body: "O brunch da manhã seguinte, as partidas e uma última oferta. O casamento encerra como começou — em silêncio, à mão." },
      ],
    },
    audience: {
      eyebrow: "Para quem é",
      headline: "Será isto *para si?*",
      items: [
        { title: "Casais que se casam no estrangeiro", body: "Um casamento num país onde nenhum dos dois vive — onde precisa de um ateliê que conheça o terreno." },
        { title: "De quarenta a oitocentos convidados", body: "O nosso mínimo é quarenta. Abaixo disso, encaminhamo-lo, com gosto, para um ateliê especializado em casamentos íntimos." },
        { title: "Dezoito meses ou mais", body: "O serviço integral precisa de tempo. Se está dentro do ano, fale connosco — mas o calendário aperta." },
        { title: "De vários dias, muitas vezes multicultural", body: "A maioria dos nossos casamentos estende-se por três a cinco dias, e cerca de metade entrelaça duas culturas ou duas religiões." },
        { title: "Casais que querem ser convidados", body: "No seu próprio casamento. O ateliê sustenta o trabalho para que possa estar presente nele." },
      ],
    },
    faq: {
      eyebrow: "Perguntas, respondidas",
      headline: "Perguntas *frequentes.*",
      items: [
        { question: "Quanto custa o serviço de planeamento integral?", answer: ["O ateliê trabalha com uma tarifa fixa de planeamento, ajustada ao casamento — normalmente entre 12 e 18 % do orçamento total, acordada à partida e sem comissão sobre os fornecedores. Partilhamos um orçamento transparente por rubricas na primeira proposta, e nunca retiramos uma margem oculta sobre um florista ou um catering."] },
        { question: "Quantos casamentos aceitam de cada vez?", answer: ["Catorze por ano, em todo o ateliê. A cada um são atribuídos dois planeadores que o sustentam desde a primeira conversa até à despedida. Limitamos o calendário de propósito — é a única forma de estar presente em cada evento de cada dia."] },
        { question: "Podem trabalhar connosco se já tivermos espaço?", answer: ["Sim. Muitos casais chegam com o espaço já escolhido. Adaptamos os nossos outros serviços — design, protocolo cultural, produção, experiência do convidado — em torno do espaço que tem. A tarifa de planeamento ajusta-se em conformidade."] },
        { question: "Viajam para qualquer lugar ou apenas para Punta Cana?", answer: ["Temos base em Punta Cana e Milão, e viajamos por todo o mundo. Cerca de metade dos nossos casamentos são nas Caraíbas; os restantes abrangem Itália, França, Espanha, Grécia, as Caraíbas mais amplas e, por vezes, mais além."] },
        { question: "Com quanta antecedência devemos contratá-los?", answer: ["Dezoito a vinte e quatro meses é o ideal. Dá tempo para assegurar o espaço certo, desenvolver um design à medida e ensaiar a logística como deve ser. Já planeámos casamentos em seis meses — mas o calendário, e as opções de espaço, apertam depressa."] },
      ],
    },
    cta: {
      eyebrow: "Uma conversa privada —",
      headline: "*Comece* a sua jornada nupcial.",
      body: "Diga-nos o casamento que imagina, o destino e uma data aproximada. Grecia responde pessoalmente em cinco dias úteis.",
      ctaLabel: "Solicitar uma consulta privada →",
    },
  },

  de: {
    name: "Zielhochzeitsplanung",
    summary:
      "Rundum-Kuratierung vom Kontinent bis zum Teller, achtzehn bis vierundzwanzig Monate im Voraus.",
    hero: {
      eyebrow: "Leistungen · Nr. 01",
      scriptOverline: "Die vollständige",
      headline: "*Planung.*",
      deck: "Das vollständige Engagement — achtzehn bis vierundzwanzig Monate, von Anfang bis Ende, vom ersten Gespräch bis zum Brunch am Morgen danach.",
      captionLeft: "Die Vorzeigeleistung des Ateliers",
      captionCenter: "Rundum-Service · zwei Planer pro Hochzeit",
      captionRight: "Tafel I",
    },
    overview: {
      eyebrow: "Die Leistung",
      headline: "Vom Kontinent zum *Teller.*",
      lede: "Die Zielhochzeitsplanung ist die Vorzeigeleistung des Ateliers — das vollständige Engagement, bei dem wir jeden Teil der Hochzeit vom ersten Gespräch bis zum letzten Abschied tragen.",
      bodyParagraphs: [
        "Eine Zielhochzeit ist keine ins Ausland verlegte heimische Hochzeit. Sie ist eine andere Disziplin: eine reisende Gästeliste, ein Ort, den man nicht aus einer Laune heraus besuchen kann, Dienstleister in einer fremden Sprache, rechtliche Anforderungen, die sich an jeder Grenze ändern, und ein Kalender, der in Jahren statt in Monaten gemessen wird.",
        "Wir haben diese Hochzeit zweihundertvierzig Mal geplant. Wir wissen, welche Resorts ihre Kapazität überschätzen, welche Flughäfen Blumenimporte ohne Verzögerung abfertigen und wie man einen viertägigen Bogen zusammenhält, wenn dreihundert Gäste von drei Kontinenten anreisen.",
      ],
      captionLine1: "Cap Cana · Februar 2025",
      captionLine2: "Die Hochzeit von Saira & Adam",
    },
    inclusions: {
      eyebrow: "Was es umfasst",
      headline: "Getragen, *von Anfang bis Ende.*",
      deck: "Das Rundum-Engagement bindet jede einzelne Spezialleistung des Ateliers standardmäßig ein.",
      items: [
        { title: "Locationsuche", body: "Eine engere Auswahl von drei bis fünf Häusern, persönlich besichtigt, abgestimmt auf Ihre Gästezahl und die Hochzeit, die Sie sich vorstellen." },
        { title: "Design & künstlerische Leitung", body: "Floristik, Tafel, Licht, Duft, Klang — ein vollständiges visuelles Konzept, maßgeschneidert für die Hochzeit." },
        { title: "Kulturelles Protokoll", body: "Geistliche, Choreografen und Caterer für jede Tradition, koordiniert von unseren Kulturspezialisten." },
        { title: "Gästelogistik", body: "Zimmerkontingente, Transfers, Empfangsschalter, Ausflüge, Geschenke und Abschiedsbrunches — das vollständige Erlebnis des reisenden Gastes." },
        { title: "Recht & Papierkram", body: "Eheurkunden, Apostillen, Zollabfertigung für Blumen und Zeremonialobjekte, Konformität in mehreren Ländern." },
        { title: "Produktion", body: "Bühne, Ton, Licht, AV, Bau und Feuerwerk — ausgeführt vom eigenen Produktionsteam des Ateliers." },
        { title: "Budget & Dienstleister", body: "Ein transparentes Budget nach Posten, geprüfte Verträge, gemanagte Dienstleister, geplante Zahlungen." },
        { title: "Leitung vor Ort", body: "Grecia und ein zweiter Planer bei jedem Programmpunkt jedes Tages vor Ort. Nichts wird über das Atelier hinaus delegiert." },
        { title: "Das Jahr dazwischen", body: "Monatliche Abstimmungen, ein gemeinsames Planungsportal und ein einziger Ansprechpartner, der Ihre Hochzeit auswendig kennt." },
      ],
    },
    process: {
      eyebrow: "Der Ablauf",
      headline: "Sechs *Sätze.*",
      deck: "Wie sich eine Zielhochzeit vom ersten Gespräch bis zum Brunch am Morgen danach bewegt, über achtzehn bis vierundzwanzig Monate.",
      steps: [
        { numeral: "I", title: "Das Gespräch", when: "24 – 22 Monate vorher", body: "Eine private Beratung, zwei bis drei Stunden. Wir hören zu — Ihnen, Ihren Familien, der Hochzeit, die Sie sich vorstellen — und sagen Ihnen ehrlich, was möglich ist." },
        { numeral: "II", title: "Konzept & Ort", when: "22 – 18 Monate vorher", body: "Ein schriftliches Konzept, ein Arbeitsbudget und eine engere Auswahl persönlich besichtigter Orte. Wir verfeinern, bis die Richtung stimmt, und sichern dann das Datum." },
        { numeral: "III", title: "Design & Beschaffung", when: "18 – 10 Monate vorher", body: "Das maßgeschneiderte Design entwickelt sich — Floristik, Tafel, Palette, Produktion. Kulturspezialisten werden engagiert. Dienstleister werden namentlich beauftragt." },
        { numeral: "IV", title: "Logistik & Gäste", when: "10 – 4 Monate vorher", body: "Zimmerkontingente, Transfers, das Gästeportal, Diätkartierung, rechtliche Unterlagen. Der viertägige Bogen wird auf dem Papier geprobt, Stunde für Stunde." },
        { numeral: "V", title: "Die Hochzeit", when: "Das Wochenende selbst", body: "Grecia und ein zweiter Planer bei jedem Programmpunkt jedes Tages. Das Atelier hält die Hochzeit, damit die Familie es nicht tun muss." },
        { numeral: "VI", title: "Der Abschied", when: "Danach", body: "Der Brunch am Morgen danach, die Abreisen und ein letztes Geschenk. Die Hochzeit schließt, wie sie begann — leise, von Hand." },
      ],
    },
    audience: {
      eyebrow: "Für wen es ist",
      headline: "Ist das *für Sie?*",
      items: [
        { title: "Paare, die im Ausland heiraten", body: "Eine Hochzeit in einem Land, in dem keiner von Ihnen lebt — wo Sie ein Atelier brauchen, das den Boden kennt." },
        { title: "Vierzig bis achthundert Gäste", body: "Unser Minimum ist vierzig. Darunter verweisen wir Sie herzlich an ein Atelier, das auf Elopements spezialisiert ist." },
        { title: "Achtzehn Monate oder mehr", body: "Der Rundum-Service braucht Zeit. Wenn Sie innerhalb eines Jahres sind, sprechen Sie mit uns — doch der Kalender schrumpft." },
        { title: "Mehrtägig, oft multikulturell", body: "Die meisten unserer Hochzeiten erstrecken sich über drei bis fünf Tage, und etwa die Hälfte verflicht zwei Kulturen oder zwei Religionen." },
        { title: "Paare, die Gäste sein wollen", body: "Bei ihrer eigenen Hochzeit. Das Atelier trägt die Arbeit, damit Sie dabei sein können." },
      ],
    },
    faq: {
      eyebrow: "Fragen, beantwortet",
      headline: "Häufig *gefragt.*",
      items: [
        { question: "Was kostet der Rundum-Planungsservice?", answer: ["Das Atelier arbeitet mit einer pauschalen Planungsgebühr, skaliert auf die Hochzeit — in der Regel 12 bis 18 % des gesamten Hochzeitsbudgets, im Voraus vereinbart und ohne Provision auf Dienstleister. Wir teilen bereits im ersten Angebot ein transparentes Budget nach Posten und nehmen nie eine versteckte Marge auf einen Floristen oder Caterer."] },
        { question: "Wie viele Hochzeiten übernehmen Sie gleichzeitig?", answer: ["Vierzehn pro Jahr, im gesamten Atelier. Jeder werden zwei Planer zugeteilt, die sie vom ersten Gespräch bis zum Abschied tragen. Wir begrenzen den Kalender bewusst — nur so können wir bei jedem Programmpunkt jedes Tages vor Ort sein."] },
        { question: "Können Sie uns buchen, wenn wir bereits einen Ort haben?", answer: ["Ja. Viele Paare kommen mit einem bereits gewählten Ort zu uns. Wir legen unsere übrigen Leistungen — Design, kulturelles Protokoll, Produktion, Gästeerlebnis — um den Ort, den Sie haben. Die Planungsgebühr passt sich entsprechend an."] },
        { question: "Reisen Sie überallhin oder nur nach Punta Cana?", answer: ["Wir sind in Punta Cana und Mailand ansässig und reisen weltweit. Etwa die Hälfte unserer Hochzeiten findet in der Karibik statt; der Rest erstreckt sich über Italien, Frankreich, Spanien, Griechenland, die weitere Karibik und gelegentlich darüber hinaus."] },
        { question: "Wie weit im Voraus sollten wir Sie engagieren?", answer: ["Achtzehn bis vierundzwanzig Monate sind ideal. Das gibt Zeit, den richtigen Ort zu sichern, ein maßgeschneidertes Design zu entwickeln und die Logistik ordentlich zu proben. Wir haben Hochzeiten in sechs Monaten geplant — doch der Kalender und die Ortsoptionen schrumpfen schnell."] },
      ],
    },
    cta: {
      eyebrow: "Ein privates Gespräch —",
      headline: "*Beginnen* Sie Ihre Hochzeitsreise.",
      body: "Erzählen Sie uns von der Hochzeit, die Sie sich vorstellen, vom Ziel und von einem ungefähren Datum. Grecia antwortet persönlich innerhalb von fünf Werktagen.",
      ctaLabel: "Privates Gespräch anfragen →",
    },
  },

  it: {
    name: "Organizzazione Matrimoni di Destinazione",
    summary:
      "Una curatela integrale, dal continente al piatto, con diciotto-ventiquattro mesi di anticipo.",
    hero: {
      eyebrow: "Servizi · N. 01",
      scriptOverline: "L'organizzazione",
      headline: "*integrale.*",
      deck: "L'impegno completo — diciotto-ventiquattro mesi, dall'inizio alla fine, dalla prima conversazione al brunch del mattino seguente.",
      captionLeft: "Il servizio di punta dell'atelier",
      captionCenter: "Servizio integrale · due organizzatori per matrimonio",
      captionRight: "Tavola I",
    },
    overview: {
      eyebrow: "Il servizio",
      headline: "Dal continente al *piatto.*",
      lede: "L'organizzazione di matrimoni di destinazione è il servizio di punta dell'atelier — l'impegno completo, in cui reggiamo ogni parte del matrimonio dalla prima conversazione all'ultimo commiato.",
      bodyParagraphs: [
        "Un matrimonio di destinazione non è un matrimonio locale trasferito all'estero. È una disciplina diversa: una lista di invitati che viaggia, un luogo che non si può visitare per capriccio, fornitori in un'altra lingua, requisiti legali che cambiano a ogni confine e un calendario misurato in anni anziché in mesi.",
        "Abbiamo organizzato questo matrimonio duecentoquaranta volte. Sappiamo quali resort sovrastimano la propria capienza, quali aeroporti sdoganano le importazioni floreali senza ritardo e come tenere insieme un arco di quattro giorni quando trecento invitati viaggiano da tre continenti.",
      ],
      captionLine1: "Cap Cana · Febbraio 2025",
      captionLine2: "Il matrimonio di Saira & Adam",
    },
    inclusions: {
      eyebrow: "Cosa comprende",
      headline: "Retto, *dall'inizio alla fine.*",
      deck: "L'impegno integrale include di serie ciascuno dei servizi specialistici dell'atelier.",
      items: [
        { title: "Ricerca location", body: "Una rosa di tre-cinque dimore, perlustrate di persona, calibrate sul numero di invitati e sul matrimonio che immaginate." },
        { title: "Design e direzione artistica", body: "Fiori, mise en place, luce, profumo, suono — un concept visivo completo creato su misura per il matrimonio." },
        { title: "Protocollo culturale", body: "Celebranti, coreografi e catering per qualsiasi tradizione, coordinati dai nostri specialisti culturali." },
        { title: "Logistica degli invitati", body: "Blocchi di camere, transfer, desk di benvenuto, escursioni, omaggi e brunch di commiato — l'esperienza completa dell'invitato che viaggia." },
        { title: "Legale e pratiche", body: "Licenze di matrimonio, apostille, sdoganamento di fiori e oggetti cerimoniali, conformità in più paesi." },
        { title: "Produzione", body: "Palco, audio, luci, AV, allestimento e fuochi d'artificio — gestiti dal team di produzione interno dell'atelier." },
        { title: "Budget e fornitori", body: "Un budget trasparente per voci, contratti revisionati, fornitori gestiti, pagamenti programmati." },
        { title: "Direzione in loco", body: "Grecia e un secondo organizzatore presenti a ogni evento di ogni giorno. Nulla viene delegato oltre l'atelier." },
        { title: "L'anno di mezzo", body: "Aggiornamenti mensili, un portale di pianificazione condiviso e un unico referente che conosce il vostro matrimonio a memoria." },
      ],
    },
    process: {
      eyebrow: "Il processo",
      headline: "Sei *movimenti.*",
      deck: "Come un matrimonio di destinazione procede dalla prima conversazione al brunch del mattino seguente, nell'arco di diciotto-ventiquattro mesi.",
      steps: [
        { numeral: "I", title: "La conversazione", when: "24 – 22 mesi prima", body: "Una consulenza privata, di due-tre ore. Ascoltiamo — voi, le vostre famiglie, il matrimonio che immaginate — e vi diciamo con onestà cosa è possibile." },
        { numeral: "II", title: "Concept e luogo", when: "22 – 18 mesi prima", body: "Un concept scritto, un budget di lavoro e una rosa di luoghi perlustrati di persona. Affiniamo finché la direzione è quella giusta, poi fissiamo la data." },
        { numeral: "III", title: "Design e selezione", when: "18 – 10 mesi prima", body: "Il design su misura si sviluppa — fiori, mise en place, palette, produzione. Vengono coinvolti gli specialisti culturali. I fornitori sono ingaggiati per nome." },
        { numeral: "IV", title: "Logistica e invitati", when: "10 – 4 mesi prima", body: "Blocchi di camere, transfer, il portale invitati, mappatura delle diete, pratiche legali. L'arco di quattro giorni viene provato sulla carta, ora per ora." },
        { numeral: "V", title: "Il matrimonio", when: "Il fine settimana stesso", body: "Grecia e un secondo organizzatore a ogni evento di ogni giorno. L'atelier regge il matrimonio così che la famiglia non debba farlo." },
        { numeral: "VI", title: "Il commiato", when: "Dopo", body: "Il brunch del mattino seguente, le partenze e un ultimo dono. Il matrimonio si chiude come è iniziato — in silenzio, a mano." },
      ],
    },
    audience: {
      eyebrow: "A chi è rivolto",
      headline: "È questo *per voi?*",
      items: [
        { title: "Coppie che si sposano all'estero", body: "Un matrimonio in un paese in cui nessuno dei due vive — dove serve un atelier che conosca il terreno." },
        { title: "Da quaranta a ottocento invitati", body: "Il nostro minimo è quaranta. Al di sotto, vi indirizziamo, con calore, a un atelier specializzato in matrimoni intimi." },
        { title: "Diciotto mesi o più", body: "Il servizio integrale richiede tempo. Se siete entro l'anno, parlatene con noi — ma il calendario si restringe." },
        { title: "Su più giorni, spesso multiculturale", body: "La maggior parte dei nostri matrimoni si estende su tre-cinque giorni, e circa la metà intreccia due culture o due religioni." },
        { title: "Coppie che vogliono essere invitate", body: "Al proprio matrimonio. L'atelier regge il lavoro così che possiate esserci." },
      ],
    },
    faq: {
      eyebrow: "Domande, con risposta",
      headline: "Domande *frequenti.*",
      items: [
        { question: "Quanto costa il servizio di organizzazione integrale?", answer: ["L'atelier lavora con un onorario fisso di organizzazione, proporzionato al matrimonio — di norma tra il 12 e il 18 % del budget complessivo, concordato in anticipo e senza commissione sui fornitori. Condividiamo un budget trasparente per voci già nella prima proposta, e non tratteniamo mai un margine nascosto su un fiorista o un catering."] },
        { question: "Quanti matrimoni accettate per volta?", answer: ["Quattordici all'anno, su tutto l'atelier. A ciascuno sono assegnati due organizzatori che lo reggono dalla prima conversazione al commiato. Limitiamo il calendario di proposito — è l'unico modo per essere presenti a ogni evento di ogni giorno."] },
        { question: "Potete seguirci se abbiamo già una location?", answer: ["Sì. Molte coppie arrivano con la location già scelta. Adattiamo i nostri altri servizi — design, protocollo culturale, produzione, esperienza degli invitati — attorno alla location che avete. L'onorario di organizzazione si adegua di conseguenza."] },
        { question: "Viaggiate ovunque o solo a Punta Cana?", answer: ["Abbiamo sede a Punta Cana e a Milano, e viaggiamo in tutto il mondo. Circa la metà dei nostri matrimoni si svolge ai Caraibi; il resto abbraccia Italia, Francia, Spagna, Grecia, i Caraibi più ampi e, a volte, oltre."] },
        { question: "Con quanto anticipo dovremmo ingaggiarvi?", answer: ["Diciotto-ventiquattro mesi è l'ideale. Dà il tempo di assicurare la location giusta, sviluppare un design su misura e provare la logistica come si deve. Abbiamo organizzato matrimoni in sei mesi — ma il calendario, e le opzioni di location, si restringono in fretta."] },
      ],
    },
    cta: {
      eyebrow: "Una conversazione privata —",
      headline: "*Inizia* il tuo viaggio nuziale.",
      body: "Raccontaci il matrimonio che immagini, la destinazione e una data indicativa. Grecia risponde personalmente entro cinque giorni lavorativi.",
      ctaLabel: "Richiedi una consulenza privata →",
    },
  },
};
